name: luxent_shop
description: A luxurious e-commerce app built with Flutter.

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  http: ^0.13.6
  image_picker: ^1.0.4  # <-- Added for image picking

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo1.jpg
    - assets/women.png
    - assets/men.png
    - assets/kids.png
    - assets/curve.png
    - assets/homeDecor.png
    - assets/smartPhones.png
    - assets/gaming.png
    - assets/product1.png
    - assets/jupe.png
    - assets/robe.png
    - assets/soiree.png
    - assets/soiree2.png
    - assets/pijama.png
    - assets/pontalon.png
    - assets/kamis.png
    - assets/chemise.png
    - assets/tshirt.png
    - assets/cascette.png
    - assets/cartable.png
